# Generated by Django 6.0.6 on 2026-07-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_teacher_assigned_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='closing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='opening_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
