# Generated by Django 6.1 on 2026-08-11 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='schoolprofile',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='schoolprofile',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='schoolprofile',
            name='closing_date',
        ),
        migrations.RemoveField(
            model_name='schoolprofile',
            name='opening_date',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='hire_date',
        ),
        migrations.AlterField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.student'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.student'),
        ),
        migrations.AlterField(
            model_name='message',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_app.class'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='assigned_classes',
            field=models.ManyToManyField(blank=True, to='school_app.class'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='school_app.subject'),
        ),
        migrations.DeleteModel(
            name='AcademicHistory',
        ),
    ]
